### ISSUE TITLE
trained weights

### ISSUE THREAD

**Issue by fyting** [whyang78/iCAN_PyTorch#2]
Hi, can you share the trained weigths on HICO and VCOCO, thank you.

**Comment by whyang78** [comment]
> Hi, can you share the trained weigths on HICO and VCOCO, thank you.

sorry, The project was completed a long time ago. So those files could not be found.

**Comment by fyting** [comment]
okay.  Can the trained model achieve the effect of the original paper?

**Comment by fyting** [comment]
> > Hi, can you share the trained weigths on HICO and VCOCO, thank you.
> 
> sorry, The project was completed a long time ago. So those files could not be found.

您好，您可以给个联系方式吗，我在训练过程中遇到一些问题想请教一下，谢谢了
